### ISSUE TITLE
Can't install OroCRM from scratch with installed EltrinoOroCRMEbayBundle

### ISSUE THREAD

**Issue by yshyshkin** [eltrino/EltrinoOroCRMEbayBundle#10]
Installation fails during migration loading with error:

```
  > OroCRM\Bundle\MagentoBundle\Migrations\Schema\OroCRMMagentoBundleInstaller
    ERROR: The column 'wsdl_url' on table 'oro_integration_transport' already exists.
```

The issue appears because EltrinoOroCRMEbayBundle (priority=20) loads before OroCRMMagentoBundle (priority = 50). Would be good to load EltrinoOroCRMEbayBundle bundle after OroCRMMagentoBundle.

**Comment by odi-um** [comment]
Fixed and release created.
