### ISSUE TITLE
Error when trying to run sync after installation

### ISSUE THREAD

**Issue by Sparesbox** [eltrino/EltrinoOroCRMEbayBundle#5]
We have installed the Ebay Integraiton and setup the configuration in Oro.  

After selecting the connectors as selected we run a sync, the following error is then reported:

PHP Fatal error:  Call to undefined method Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor::initialize() in <omitted>/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Step/ItemStep.php on line 232

**Comment by odi-um** [comment]
Hi Sparesbox,

Could you specify which version of OroCRM you are using ? 

Currently we are working on upgrade for this bundle to improve it for the latest OroCRM. It could be that your issues related to this task.

Thank you.

**Comment by Sparesbox** [comment]
Hi odi-um,

We are currently running version 1.7.6 of OroCRM.

Cheers.

**Comment by odi-um** [comment]
Thanks, as i thought.
